disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "厚嘴棉凫窝"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/logo.svg"

  [params.author]
    name = "Sean Enderby"
    image = "img/logo.png"
    links = [
      { github = "https://github.com/seanlikeskites" }
    ]
