disabled = false
languageCode = "zh-cn"
languageName = "中文"
weight = 2
title = "厚嘴棉凫窝"

[params]
  displayName = "中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/logo.svg"

  [params.author]
    name = "Sean Enderby"
    image = "img/logo.png"
    links = [
      { github = "https://github.com/seanlikeskites" }
    ]
