disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Sean Enderby"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/logo.svg"
